### ISSUE TITLE
(unicode error)

### ISSUE THREAD

**Issue by Laksmi1940** [shreyans29/thesemicolon#1]
![untitled](https://cloud.githubusercontent.com/assets/26248147/23654910/e55c19b0-0358-11e7-836c-cf8f2181d7b5.png)

hii..I am new to this word2vec world. when I ran your code,it shows error. can you  please help me. I have uploaded the error  snap.Any help can be appreciated.

**Comment by shreyans29** [comment]
Hi, This is an error with escaping slash try this , C:\\Users\\Acer\\Desktop . 
Another thing to note is my code is written in python 2.7 and you are using python 3 and that is why you are experiencing the error.

**Comment by Laksmi1940** [comment]
hii....thank you for your response..I tried using the slash but it didn't work. Can u please tell me  how can I modify this  code so that it will  run in python 3.5. Here I am attaching the original code snapshot.

![untitled](https://cloud.githubusercontent.com/assets/26248147/23660226/bf83d230-036e-11e7-84ff-1be89e7eeb4a.png)

**Comment by shreyans29** [comment]
one of these three has to work. Most of the other code will remain the same in python 3. 

os.chdir(r'C:\Users\Acer\Desktop')
os.chdir('C:\\Users\\Acer\\Desktop')
os.chdir('C:/Users/Acer/Desktop')
