### ISSUE TITLE
Error in CNNs (Keras)

### ISSUE THREAD

**Issue by Dakshster** [shreyans29/thesemicolon#3]
After executing the code, it reads the files completely but at the end it gives an error as it cannot flatten.

Error - 
`The shape of the input to "Flatten" is not fully defined (got (0, 24, 32). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.`

**Comment by Dakshster** [comment]
Fixed it in https://github.com/shreyans29/thesemicolon/pull/4

**Comment by shreyans29** [comment]
Setting dimension order as th is something you can do permanently by changing /.keras/keras.json file.  However this change will make it run everywhere. Thanks.

**Comment by Dakshster** [comment]
Yea, but it makes it work at the end of the day 👍
